# Alertmanager Configuration
# DevOps/SRE Engineer - 20 лет опыта

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@samokoder.com'
  smtp_auth_username: 'alerts@samokoder.com'
  smtp_auth_password: '${SMTP_PASSWORD}'

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing tree
route:
  group_by: ['alertname', 'service', 'signal']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
      routes:
        # P0 - Immediate escalation
        - match:
            severity: critical
            signal: latency
          receiver: 'p0-oncall'
          group_wait: 0s
          repeat_interval: 15m
        - match:
            severity: critical
            signal: errors
          receiver: 'p0-oncall'
          group_wait: 0s
          repeat_interval: 15m
        - match:
            severity: critical
            signal: saturation
          receiver: 'p0-oncall'
          group_wait: 0s
          repeat_interval: 15m
        - match:
            signal: availability
          receiver: 'p0-oncall'
          group_wait: 0s
          repeat_interval: 10m

    # Warning alerts - delayed notification
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 2h

    # Business metrics - daily summary
    - match:
        service: business
      receiver: 'business-alerts'
      group_wait: 1h
      repeat_interval: 24h

# Inhibition rules
inhibit_rules:
  # Inhibit warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'signal']

  # Inhibit individual service alerts when the entire service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: 'High.*Latency|High.*ErrorRate|High.*Usage'
    equal: ['service']

# Receivers
receivers:
  # Default receiver for unmatched alerts
  - name: 'default-receiver'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts'
        title: 'Samokoder Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true

  # P0 On-call alerts - immediate escalation
  - name: 'p0-oncall'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#p0-alerts'
        title: '🚨 P0 CRITICAL ALERT'
        text: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Signal:** {{ .Labels.signal }}
          **Severity:** {{ .Labels.severity }}
          **Runbook:** {{ .Annotations.runbook_url }}
          {{ end }}
        send_resolved: true
        color: 'danger'
    
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_ROUTING_KEY}'
        description: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        details:
          service: '{{ .Labels.service }}'
          signal: '{{ .Labels.signal }}'
          severity: '{{ .Labels.severity }}'
          runbook: '{{ .Annotations.runbook_url }}'
    
    email_configs:
      - to: 'oncall@samokoder.com'
        subject: '🚨 P0 CRITICAL: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Signal: {{ .Labels.signal }}
          Severity: {{ .Labels.severity }}
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}

  # Critical alerts - immediate notification
  - name: 'critical-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#critical-alerts'
        title: '🔴 CRITICAL ALERT'
        text: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Signal:** {{ .Labels.signal }}
          {{ end }}
        send_resolved: true
        color: 'danger'
    
    email_configs:
      - to: 'devops@samokoder.com'
        subject: '🔴 CRITICAL: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Signal: {{ .Labels.signal }}
          {{ end }}

  # Warning alerts - delayed notification
  - name: 'warning-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#warning-alerts'
        title: '⚠️ WARNING ALERT'
        text: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Signal:** {{ .Labels.signal }}
          {{ end }}
        send_resolved: true
        color: 'warning'
    
    email_configs:
      - to: 'devops@samokoder.com'
        subject: '⚠️ WARNING: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Signal: {{ .Labels.signal }}
          {{ end }}

  # Business metrics alerts
  - name: 'business-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#business-metrics'
        title: '📊 Business Alert'
        text: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Signal:** {{ .Labels.signal }}
          {{ end }}
        send_resolved: true
        color: 'good'
    
    email_configs:
      - to: 'product@samokoder.com'
        subject: '📊 Business Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Signal: {{ .Labels.signal }}
          {{ end }}

  # No-op receiver for testing
  - name: 'null'