---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager
rules:
- apiGroups: [""]
  resources:
  - secrets
  - configmaps
  - events
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["cert-manager.io"]
  resources:
  - certificates
  - certificaterequests
  - issuers
  - clusterissuers
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["acme.cert-manager.io"]
  resources:
  - challenges
  - orders
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
