---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
spec:
  type: ClusterIP
  ports:
  - port: 9402
    targetPort: 9402
    name: http
  selector:
    app: cert-manager
