---
apiVersion: v1
kind: Service
metadata:
  name: cost-monitoring
  namespace: monitoring
  labels:
    app: cost-monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9003
    targetPort: 9003
    name: http
  selector:
    app: cost-monitoring
