---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: monitoring
type: Opaque
data:
  access-key-id: QUtJQUlPU0ZPRE5UREVYQUtL  # AKIAIOSFODNTDEXAKK
  secret-access-key: d0JhbGx6SldUWHVYVXNuTkVyR2NQSEdRMFpIZ2NTRlI=  # wJallzJWThXUsnNErGcPHGQ0ZHgcSFR