---
apiVersion: v1
kind: Service
metadata:
  name: external-secrets
  namespace: external-secrets-system
  labels:
    app: external-secrets
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8081
    targetPort: 8081
    name: metrics
  selector:
    app: external-secrets