apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-flags
  namespace: samokoder
  labels:
    app: feature-flags
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-flags
  template:
    metadata:
      labels:
        app: feature-flags
    spec:
      serviceAccountName: feature-flags
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: feature-flags
        image: unleashorg/unleash-server:4.22.0
        ports:
        - containerPort: 4242
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: feature-flags-secret
              key: DATABASE_URL
        - name: DATABASE_SSL
          value: "true"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: feature-flags-secret
              key: SECRET_KEY
        - name: ADMIN_USERNAME
          value: "admin"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: feature-flags-secret
              key: ADMIN_PASSWORD
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4242
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4242
          initialDelaySeconds: 5
          periodSeconds: 5
