---
apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags-config
  namespace: samokoder
data:
  features.json: |
    {
      "features": [
        {
          "name": "new-ui",
          "enabled": false,
          "description": "New user interface",
          "strategies": [
            {
              "name": "gradualRollout",
              "parameters": {
                "percentage": 10,
                "groupId": "samokoder-users"
              }
            }
          ]
        },
        {
          "name": "ai-features",
          "enabled": true,
          "description": "AI-powered features",
          "strategies": [
            {
              "name": "default",
              "parameters": {}
            }
          ]
        },
        {
          "name": "beta-features",
          "enabled": false,
          "description": "Beta features for testing",
          "strategies": [
            {
              "name": "userWithId",
              "parameters": {
                "userIds": "user1,user2,user3"
              }
            }
          ]
        },
        {
          "name": "maintenance-mode",
          "enabled": false,
          "description": "Maintenance mode toggle",
          "strategies": [
            {
              "name": "default",
              "parameters": {}
            }
          ]
        }
      ]
    }