apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-flags
  namespace: samokoder
  labels:
    app: feature-flags
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-flags
  template:
    metadata:
      labels:
        app: feature-flags
    spec:
      serviceAccountName: feature-flags
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: feature-flags
        image: unleashorg/unleash-server:4.22.0
        ports:
        - containerPort: 4242
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: feature-flags-secret
              key: DATABASE_URL
        - name: DATABASE_SSL
          value: "true"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: feature-flags-secret
              key: SECRET_KEY
        - name: ADMIN_USERNAME
          value: "admin"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: feature-flags-secret
              key: ADMIN_PASSWORD
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4242
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4242
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: feature-flags
  namespace: samokoder
  labels:
    app: feature-flags
spec:
  type: ClusterIP
  ports:
  - port: 4242
    targetPort: 4242
    name: http
  selector:
    app: feature-flags
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: feature-flags
  namespace: samokoder
---
apiVersion: v1
kind: Secret
metadata:
  name: feature-flags-secret
  namespace: samokoder
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQGRiOjU0MzIvc2Ftb2tvZGVy  # postgresql://postgres:password@db:5432/samokoder
  SECRET_KEY: ZmVhdHVyZS1mbGFncy1zZWNyZXQta2V5  # feature-flags-secret-key
  ADMIN_PASSWORD: YWRtaW4=  # admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags-config
  namespace: samokoder
data:
  features.json: |
    {
      "features": [
        {
          "name": "new-ui",
          "enabled": false,
          "description": "New user interface",
          "strategies": [
            {
              "name": "gradualRollout",
              "parameters": {
                "percentage": 10,
                "groupId": "samokoder-users"
              }
            }
          ]
        },
        {
          "name": "ai-features",
          "enabled": true,
          "description": "AI-powered features",
          "strategies": [
            {
              "name": "default",
              "parameters": {}
            }
          ]
        },
        {
          "name": "beta-features",
          "enabled": false,
          "description": "Beta features for testing",
          "strategies": [
            {
              "name": "userWithId",
              "parameters": {
                "userIds": "user1,user2,user3"
              }
            }
          ]
        },
        {
          "name": "maintenance-mode",
          "enabled": false,
          "description": "Maintenance mode toggle",
          "strategies": [
            {
              "name": "default",
              "parameters": {}
            }
          ]
        }
      ]
    }