---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: monitoring
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/lib/docker/containers/*/*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
    
    - type: log
      paths:
        - /var/log/*.log
        - /var/log/syslog
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
    
    output.logstash:
      hosts: ["logstash.monitoring.svc.cluster.local:5044"]
    
    processors:
      - add_cloud_metadata: ~
      - add_docker_metadata: ~