---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: monitoring
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    
    filter {
      if [kubernetes] {
        mutate {
          add_field => { "cluster_name" => "samokoder" }
        }
      }
      
      if [kubernetes][labels][app] == "samokoder-backend" {
        mutate {
          add_field => { "service" => "samokoder" }
        }
      }
    }
    
    output {
      elasticsearch {
        hosts => ["elasticsearch.monitoring.svc.cluster.local:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }