---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
  namespace: prometheus-operator
  labels:
    app: prometheus-operator
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: prometheus-operator