apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "samokoder.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "samokoder.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}