apiVersion: v1
kind: Service
metadata:
  name: {{ include "samokoder.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "samokoder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    {{- include "samokoder.selectorLabels" . | nindent 4 }}